[template]

# The name of the template that will be used to render the application's configuration file
# Confd will look in `/etc/conf.d/templates` for these files by default
src = "erlang.cookie.tmpl"

# The location to place the rendered configuration file
dest = "/var/lib/rabbitmq/.erlang.cookie"

# The etcd keys or directory to watch.  This is where the information to fill in
# the template will come from.
keys = [ 
	"/rabbitmq/erlang/cookie",
]

# File ownership and mode information
mode = "0600"

# These are the commands that will be used to check whether the rendered config is
# valid and to reload the actual service once the new config is in place
#check_cmd = ""
reload_cmd = "chown rabbitmq:rabbitmq /var/lib/rabbitmq/.erlang.cookie && /usr/sbin/service rabbitmq-server reload"

